### PR TITLE
Porting to Summit

### PR DESCRIPTION
**Pull request by jayeshkrishna**
This PR includes fixes for porting PIO2 to Summit (@OLCF),

* Minor fix to support IBM compiler
* CMake changes and mpiexec script for Summit

### CODE REVIEW

**Comment by dqwu** [comment]
For build issues with IBM compiler, are they also reproducible on Mira/Cetus?
Just wonder why they have not been noticed for a long time before Summit is available.

**Comment by dqwu** [comment]
For Summit, why do we need cmake_host_system_information and FQDN_SITENAME?
If the existing SITENAME can be reused, the logic will be similar as before:
```
    # NCSA Machine (Blue Waters)
    elseif (SITENAME MATCHES "^h2ologin")

        set (${RETURN_VARIABLE} "ncsa" PARENT_SCOPE)

    # OLCF/Oak Ridge Machines
    elseif (SITENAME MATCHES "^eos" OR
            SITENAME MATCHES "^titan")

        set (${RETURN_VARIABLE} "olcf" PARENT_SCOPE)

    # Summit (OLCF)
    elseif (SITENAME MATCHES "^summit")

        set (${RETURN_VARIABLE} "summit" PARENT_SCOPE)
        
    else ()

        set (${RETURN_VARIABLE} "unknown" PARENT_SCOPE)
    
    endif ()
```

**Comment by jayeshkrishna** [comment]
No, the old logic (site_name/hostname) does not work for Summit. You need to get the fully qualified domain name to determine if its a summit login node.

**Comment by dqwu** [comment]
@jayeshkrishna 
This change has caused a lot of CMake configure warnings in CDash:
```
CMake Warning at cmake/LibMPI.cmake:75 (message):
  Unsupported system, compute003.mcs.anl.gov, using defaults
Call Stack (most recent call first):
  cmake/LibMPI.cmake:106 (platform_name)
  tests/cunit/CMakeLists.txt:138 (add_mpi_test)
```

**Comment by jayeshkrishna** [comment]
Yes, I will remove the warning message (in a new commit) and re-merge the branch

**Comment by jayeshkrishna** [comment]
@dqwu : I am planning to remerge the branch to develop, let me know if its ok with you.

**Pull request merged**
