### PR TITLE
Adding a CTest environment variable for anlworkstation

### PR DESCRIPTION
**Pull request by dqwu**
This change is for PIO CDash builds on anlworkstation.

By setting this variable, we can optionally turn on
PIO_ENABLE_INTERNAL_TIMING.

Reproduce issue #185

### CODE REVIEW

**Comment by dqwu** [comment]
@jayeshkrishna 
We can merge this PR to develop first to reproduce issue 185.
Next we can merge PR 184 to develop to fix the failed test.

**Comment by jayeshkrishna** [comment]
Are we going to have a separate build/test with internal timing turned on?

**Comment by dqwu** [comment]
Yes, I will configure ASan build to turn on PIO_ENABLE_INTERNAL_TIMING
I do not think the job run time will be increased significantly.

**Comment by jayeshkrishna** [comment]
But do we want to turn it on all the time (Have "internal timing" set for all our tests), since users typically don't use that setting (E3SM collects performance stats outside PIO - so does not set "internal timing")?

**Comment by dqwu** [comment]
It is still optional and OFF by default. We just need a nightly build
to turn it on. We can turn it on in ASan build before the issue is fixed.
Later we can move this setting to ParallelIO_master_cdash build.

**Comment by jayeshkrishna** [comment]
Ok, are you suggesting to enable it (internal timing) for all our future nightly master tests ?

**Pull request merged**
