### PR TITLE
Merge adios_support to master

### LINKED ISSUE #39: Merging adios_support to master
This issue will be used to keep track of merging
the adios_support branch to master.

This issue requires Issue #38 .

### PR DESCRIPTION
**Pull request by dqwu**
This PR adds support for ADIOS in PIO.

Fixes #39

### CODE REVIEW

**Comment by dqwu** [comment]
run_cmake_adios is a new file being added. Is it OK to add it to PIO?

For file conversion, we are using tools/adios2pio-nm by default. Should
we still keep tools/adios2pio?

**Comment by jayeshkrishna** [comment]
@dqwu : What does run_cmake_adios do? Have you tried a non-ADIOS build (A build on Cori/anlworkstation without ADIOS)?
@tkurc : Do we need tools/adios2pio (see question above)?

**Comment by dqwu** [comment]
@jayeshkrishna 
run_cmake_adio was originally created by Norbert. It is an example script
for configuring adios on the authors' machines.

I have tried a non-ADIOS build on anlworkstation (it will also be tested after
we merge this PR to develop branch). I will try it on Cori later.

**Comment by dqwu** [comment]
@jayeshkrishna @tkurc 
There are 104 commits in this PR. If some commit messages should
be updated, or if some commits can be combined (squashed), please
feel free to add your comments here.

**Comment by jayeshkrishna** [comment]
Let us merge the run_cmake_adios script for now, we need to eventually move this info to docs instead.

**Comment by jayeshkrishna** [comment]
Don't we need  tools/adios2pio to convert files offline (is there code duplication between the offline conversion tool and the conversion lib?)?

**Comment by dqwu** [comment]
@jayeshkrishna 
Some of the hard-coded lengths in ADIOS branch code are smaller than 128,
such as:
char decompname[64];
char name[32], ldim[32];
char ldims[32];

Is it OK to replace them with PIO_MAX_NAME which is 256? This will require
some extra stack size in memory.

**Comment by jayeshkrishna** [comment]
For now let us replace them with PIO_MAX_NAME, if needed we can add more constants later.

**Comment by jayeshkrishna** [comment]
Can you change the description of PR from
```This PR merges the adios_support branch to master.```
 to
```This PR adds support for ADIOS in PIO```

**Comment by dqwu** [comment]
@jayeshkrishna @tkurc 
I have noticed that the following commit might need to be reworded.
https://github.com/E3SM-Project/ParallelIO/pull/162/commits/8b85d55

The commit message is:
Moved ADIOS calls outside if (ioproc). Removed stream calls for
compilation on Titan.

The actual code change does:
1) Implements ADIOS type for some PIO functions:
PIOc_closefile()
PIOc_put_att_tc()
PIOc_put_vars_tc()
PIOc_createfile_int()

2) Adds a new wrapper function C_API_ConvertBPToNC to call C++ conversion
code during PIOc_closefile()

3) Code cleanup

Besides rewording, should we still need to find an existing commit that moved
ADIOS calls outside if (ioproc) and removed stream calls for compilation
on Titan?

**Comment by jayeshkrishna** [comment]
@tkurc needs to weigh in. I would recommend just rewording (no need to find the commit that performs the change mentioned in the commit) the commit message for now.

**Comment by tkurc** [comment]
> Do we need tools/adios2pio (see question above)? 

That can be removed. It is there for archival and historical reference purposes. 

> run_cmake_adios script for now, we need to eventually move this info to docs instead.

It can be removed. We used it to remember how to configure certain flags on different machines.

**Comment by dqwu** [comment]
@jayeshkrishna 
Based on @tkurc's comment, can we safely delete (with git remove) tools/adios2pio
and run_cmake_adios  with one more commit? After this, we can merge this PR
to develop branch for testing.

**Comment by jayeshkrishna** [comment]
Sure, please go ahead and delete the above items and merge the branch to develop (after a sanity check build)

**Comment by jayeshkrishna** [comment]
The nightly tests show a mem leak - https://my.cdash.org/viewTest.php?onlyfailed&buildid=1613332 .

**Comment by dqwu** [comment]
> The nightly tests show a mem leak - https://my.cdash.org/viewTest.php?onlyfailed&buildid=1613332 .

It is also reproducible with current master branch (adios_support branch not merged yet) if we
turn off WITH_NETCDF or WITH_PNETCDF.

I have created a new issue for this memory leak.

**Pull request merged**
