### PR TITLE
Test for writes after implicit flush

### PR DESCRIPTION
**Pull request by jayeshkrishna**
This test writes out a variable after an implicit
flush is invoked (internally in PIO) for the
previous variables.

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
We need to also verify that the "implicit flush" works as expected (setting the buffer size limit triggers an implicit flush when the buffer size exceeds the limit).

**Comment by dqwu** [comment]
In current PIO2 code, pio_buffer_size_limit (default value 10485760) is only related to pnetcdf:
```
ncmpi_buffer_attach /* tell PnetCDF the amount of space for write request cache */
ncmpi_bput_var<kind>_<type> /* post a buffered nonblocking write request to a variable */
ncmpi_inq_buffer_usage /* report the usage of the attached buffer in buffered write requests */
```

Since this test does not invoke ncmpi_bput_var calls at all, ncmpi_inq_buffer_usage will report 0 as the usage. Therefore, implicit flush will not occur as usage is 0 for the logic below:
```
int flush_output_buffer(...)
{
    ...
    /* If the user forces it, or the buffer has exceeded the size
     * limit, then flush to disk. */
    if (force || usage >= pio_buffer_size_limit)
        ...
    ...
}
```
It seems that how pio_buffer_size_limit should be used in PIO2 is not clearly clarified.

**Comment by dqwu** [comment]
> The ncmpi_bput_var\<kind\>_\<type\> family of functions is the buffered version of the nonblocking write functions ncmpi_iput_var\<kind\>_\<type\>.
> 
> The write data is buffered (cached) internally by PnetCDF and will be flushed to the file at the time of calling ncmpi_wait() or ncmpi_wait_all(). Unlike ncmpi_iput_var\<kind\>_\<type\>, once the call to this API returns, the caller is free to change the contents of write buffer. 

PIO_set_buffer_size_limit only affects this internal buffer used by pnetcdf for ncmpi_bput_var
It has nothing to do with the IO data buffer used by PIO2:
```
typedef struct file_desc_t
{
    ...
    /** Data buffer for this file. */
    void *iobuf;
    ...
}
```

**Comment by jayeshkrishna** [comment]
We need to change the behaviour so that users can set the PIO internal buffer size (could also be used as the size of the buffer in buffered writes to pnetcdf).
This PR can wait until we fix the issue in the PIO code.

**Comment by jayeshkrishna** [comment]
This PR should be ready to review/merge now (I modified the comments in the test to reflect when the data is flushed out to disk)

**Comment by jayeshkrishna** [comment]
@dqwu : Can you review this PR?

**Pull request merged**
