### PR TITLE
Adding fortran tests and missing interfaces to PIO1

### LINKED ISSUE #64: Move PIO2 tests to PIO1
Move the current PIO2 fortran tests to PIO1. This
should allow us to build+test PIO1 (and test any
changes made to PIO1)

### PR DESCRIPTION
**Pull request by jayeshkrishna**
This PR,

* Adds fortran tests and testing framework from PIO2
* Adds pio_deletefile, pio_set_log_level APIs
* Minor interface changes to be compatible with PIO2

Fixes #64

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
Note that this PR only focuses on adding the fortran tests to PIO1.

Ensuring that we fix all PIO1 failures with the test suite should happen in future issues/PRs

**Comment by jayeshkrishna** [comment]
Also note that to run the tests with PIO1 the user needs to invoke "ctest" from the <BUILD_DIR>/pio directory (This is due to the way PIO1 has always been built - all tests etc gets built in directories inside the <BUILD_DIR>/pio directory).

**Comment by jayeshkrishna** [comment]
Build script for PIO1 (for anlworkstation) :
```
#!/bin/tcsh
source /software/common/adm/packages/softenv-1.6.2/etc/softenv-aliases.csh
soft add +gcc-6.2.0
soft add +szip-2.1-gcc-6.2.0
soft add +cmake-2.8.12
soft add +mpich-3.2-gcc-6.2.0
soft add +hdf5-1.8.16-gcc-6.2.0-mpich-3.2-parallel
#soft add +netcdf-4.3.3.1c-4.2cxx-4.4.2f-parallel-gcc6.2.0-mpich3.2
soft add +netcdf-4.4.1c-4.2cxx-4.4.4f-parallel-gcc6.2.0-mpich-3.2
#soft add +pnetcdf-1.6.1-gcc-6.2.0-mpich-3.2
#setenv NETCDF_PATH /soft/apps/packages/climate/netcdf/4.3.3.1c-4.2cxx-4.4.2f-parallel/gcc-6.2.0
setenv NETCDF_PATH /soft/apps/packages/climate/netcdf/4.4.1c-4.2cxx-4.4.4f-parallel/gcc-6.2.0
#setenv PNETCDF_PATH /soft/apps/packages/climate/pnetcdf/1.6.1/gcc-6.2.0
setenv PNETCDF_PATH /soft/apps/packages/climate/pnetcdf/1.8.1/gcc-6.2.0

setenv CC mpicc
setenv CXX mpicxx
setenv FC mpif90

setenv CFLAGS '-g -O0 -std=c99'
setenv CXXFLAGS '-g -O0'
setenv FFLAGS '-ffixed-line-length-none -ffree-line-length-none -g -O0'
setenv LDFLAGS  '-L/soft/apps/packages/climate/netcdf/4.3.3.1c-4.2cxx-4.4.2f-parallel/gcc-6.2.0/lib -L/soft/apps/packages/climate/hdf5/1.8.16-parallel/gcc-6.2.0/lib -L/soft/apps/packages/climate/szip/2.1/gcc-6.2.0/lib -lnetcdf -lsz -lhdf5_hl -lhdf5 -ldl -lm -lz'
cmake \
-DPIO_ENABLE_TESTS=ON \
-DPIO_BUILD_TIMING=ON \
-DPIO_MICRO_TIMING=TRUE \
-DPIO_BUILD_STATIC_LIBS=TRUE \
-DWITH_PNETCDF:BOOL=TRUE \
-DCMAKE_INSTALL_PREFIX:PATH=/sandbox/jayesh/ParallelIO_install_pio1 \
-DGENF90_PATH:PATH=/sandbox/jayesh/genf90_pio1 \
-DBUILD_SHARED_LIBS:BOOL=OFF \
-DPIO_ENABLE_FORTRAN:BOOL=ON \
-DCMAKE_BUILD_TYPE=Debug \
-DPIO_ENABLE_LOGGING:BOOL=ON \
-DPnetCDF_PATH=/soft/apps/packages/climate/pnetcdf/1.8.1/gcc-6.2.0 \
-DNetCDF_PATH=/soft/apps/packages/climate/netcdf/4.4.1c-4.2cxx-4.4.4f-parallel/gcc-6.2.0 \
-DHDF5_PATH:PATH=/soft/apps/packages/climate/hdf5/1.8.16-parallel/gcc-6.2.0 \
-DLIBZ_PATH:PATH=/soft/apps/packages/climate/szip/2.1/gcc-6.2.0 \
-LH \
/sandbox/jayesh/ParallelIO_master |& tee configure.log

make VERBOSE=1 timing |& tee make_timing.log
make VERBOSE=1 |& tee make.log
make VERBOSE=1 tests |& tee make_tests.log


```

**Comment by jayeshkrishna** [comment]
You can run ctest from the <BUILD_DIR>/pio directory to run the tests

**Comment by jayeshkrishna** [comment]
I just added the most significant changes in the PR title, what would you prefer as the title?

**Comment by dqwu** [comment]
Maybe something like "Adding fortran tests to PIO1 and porting some features from PIO2"

**Comment by jayeshkrishna** [comment]
How about "Adding fortran tests and missing interfaces to PIO1" ?

**Comment by dqwu** [comment]
That looks better, thanks.

**Pull request merged**
