### PR TITLE
Filter I/O decompositions that are saved using reg exp

### LINKED ISSUE #115: Support saving specific decomposition files
Currently the only option available is to save/dump all decomposition
files. We need a mechanism to save specific I/O decomposition
files. 

The I/O decomposition files to be saved can be specified in different
ways,

1) ioid : The unique id used to identify the I/O decomposition, or a
    regular expression to specify a range of ioids
2) Regular expression for a variable name that uses the decomposition
3) Regular expression for a file name that includes variables that use the
    decomposition
4) A regular expression that combines (1), (2) and (3) to specify the 
    decomposition to be saved.

### PR DESCRIPTION
**Pull request by jayeshkrishna**
This PR adds support for saving I/O decompositions specified
by the user using custom regular expressions. 
The I/O decompositions that are saved can be filtered based on
ioid, variable name (I/O decomposition used to read/write a
variable) and file names (I/O decompositions used to read/write
variables in a file).

Fixes #115

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
This change should not impact (in a major way) users that do not want to dump I/O decompositions.

This commit includes changes that requires a C++ compiler and also changes the C++ build environment for PIO. So these changes can potentially affect (require change in build environment etc) applications using PIO.

**Comment by dqwu** [comment]
@jayeshkrishna 
This CMake logic has an issue:
```
if (CMAKE_VERSION VERSION_LESS "3.1")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
else ()
  set(CMAKE_CXX_STANDARD 11)
endif ()
```
On my laptop CMake version is 3.5.2 and GCC version is 5.4.0
```
In file included from /usr/include/c++/5/regex:35:0,
                 from src/clib/pio_sdecomps_regex.cpp:4:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
```
Using "set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11") works.

When CMake version is 3.1 or higher, the above logic works for GCC 6.2.0 but not for GCC 5.4.0

**Comment by dqwu** [comment]
I think we can always use (without using CMake 3.1 or higher feature CMAKE_CXX_STANDARD)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
This works as long as the C++ compiler supports C++ 11.

**Comment by dqwu** [comment]
@jayeshkrishna 
PS, since CXX=mpicxx is now required to build PIO, you might need to update
README.md and some text files under doc/source (e.g. mach_walkthrough.txt
and Installing.txt)

In current README.md, the example command is out of date:
```
CC=mpicc FC=mpif90 cmake [-DOPTION1=value1 -DOPTION2=value2 ...] /path/to/pio/source
```

**Comment by dqwu** [comment]
There are build errors when PIO_ENABLE_COVERAGE is ON, because
gcov flags are not set to CMAKE_CXX_FLAGS. That is a separate issue
and I I will fix it after this PR is merged to master branch.

**Comment by jayeshkrishna** [comment]
I can increase the cmake version to 3.6 (I had similar issues with the intel compiler on Cori - apparently CMake does not support all platforms+compilers combinations in 3.1 ) or do we just delete the cmake logic (just update compiler flags)?

I will also update the README and related docs to reflect the C++ requirements too.

**Comment by dqwu** [comment]
I think we can delete the cmake logic so far (CMAKE_CXX_STANDARD does not always work)
After you rebase this feature branch, we can merge it to master.

**Comment by jayeshkrishna** [comment]
Ok, let us get rid of the cmake logic then.
I will update (add commits instead of rebase, since we already merged to develop) the branch and remerge to develop.

**Comment by jayeshkrishna** [comment]
The branch was remerged to next and should have the fixes discussed above.

**Comment by dqwu** [comment]
@jayeshkrishna 
You might also need to apply "CXX=mpicxx" to line 427 and 438 of doc/source/mach_walkthrough.txt

**Comment by jayeshkrishna** [comment]
ok, thanks. Updating lines 427 and 438 . 
Are there any other updates that I missed ?

**Comment by jayeshkrishna** [comment]
The branch should now be remerged (with the requested changes) to develop.

**Pull request merged**
